sudo: true
os: trusty
cache: false
env:
  matrix:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
  global:
  - secure: RN5rw9tGVKAWqBjvoHzK6GvZEBjNnymss/BAw7Adsvzy08kFf4YRgo5qiq+1lEPR4hhyhA27ilEp8R5iTRenaIgrXxiBvLEYxP65xgbr6s0cr3VkjxpHmwnj0dKlOWYLvS5tLHbDias9D+khzQalkA58wfn4dMmXuwGp2zNwOw3YcKkypgOY2uaJD5rCD3TvcVuJxnMVPd/4ce5iS5L0eZIGbolMl7WzzO5M8MnWwfILEfAYqRxkvvut/eHlWm70yBhZH0KiIRC1r8cLgFEzh8reLHNS0Aq4cSs8N68OZ/qZc5FyCfxE+p719cnVmuCzVXDwAkKgu5wjNkcWyLNEtXLapgU09I13HwG8UWVLj6tBg3X51dcxRuaIJ8pwRESYhsNapyc8+Hz9sagfLo9dVaUx37BAM2peYfuKgTu9oTJyh2+IB8wTE5/NDdiFYIwCXggUIpxXM6HTUtFXEJBvpYOKfycvyi1P3tLLBHV+NQtrdMmfjyPUuUEOGYzx1Ts1WaCQBBRkaffSPmoK1WbPFn6het4idftZmKvxlwYIKdmjs8jZj5/88dyMAqGilLhHJBpE0WFcNQvwiuRVoIXfxYWxm//pg/8b73ZYPoEkrjMjmJFCsbnhnnG14V/5FDO9obS+gptkEsURacOcrc+BzoNASrn2rtmYpjn37IOh7CE=
before_install:
- openssl aes-256-cbc -k "$super_secret_password" -in assets/server.key -out assets/server.key.enc
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg
script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg --wait
  2
- sfdx force:org:display -u ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg --wait 10
- sfdx force:org:delete -u ciorg -p
